### ISSUE TITLE
failed to resolve a symlink folder

### ISSUE THREAD

**Issue by ilnerdchuck** [Coen-Townson/vscode-selector#1]
I wanted to use a symlink folder, the output is a blank spot that starts an empty code workspace. i fixed adding a slash to the workspace folder default path if a vscode one is not found.
`VSCODE_WORKSPACES_PATH="$HOME/vscode-workspaces/"`

if you want to fix it 

Nice work btw

**Comment by Coen-Townson** [comment]
Ah great catch thanks! Happy to know its being used haha!
